
import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"])

import { Outfit } from "next/font/google";
import "./globals.css";

import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";



const OutfitFont = Outfit({
  subsets: ["latin"],
});
// english alph(latin), greek, arabic, bengali



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className}  h-full antialiased`}
    >
      <body>
    <Navbar />
        <main className="max-w-7xl mx-auto">{children} 
          
        </main>
        <Footer/>

      </body>
    </html>
  );
}
